### ISSUE TITLE
Disabling autoresizing mask breaks layout of superview

### ISSUE THREAD

**Issue by akolov** [robb/Cartography#101]
Starting from 79b11ffd4a17148da8ad7bceafb994a903d3e7cd layout of superview is affected.
For example, we use Cartography to layout subviews in UIPresentationController's containerView, which is provided by the controller and has translatesAutoresizingMaskIntoConstraints == false, and obviously has no layout constraints set.

On the left side is the view before changes, and after is on the right side.
![x](https://cloud.githubusercontent.com/assets/142354/6707062/90844e6c-cd63-11e4-858f-0117c83195ae.png)

As you can see containerView just collapsed to minimal possible size.

**Comment by robb** [comment]
Yeah, it's being fixed in #99

**Comment by akolov** [comment]
That was super fast! Thank you a lot! :)
