### ISSUE TITLE
CocoaPods iOS 7 support

### ISSUE THREAD

**Issue by zdenektopic** [robb/Cartography#107]
It works, frameworks are weak linked if the deployment target is below 8.0

Can you update the podspec?

**Comment by robb** [comment]
I don't really want to officially keep supporting iOS 7 if we're closer in time to iOS 9 than 7. Have you considered using a local podspec?

**Comment by robb** [comment]
The new properties in #93 are iOS 8 exclusive, so that ship has sailed I'm afraid.
