### ISSUE TITLE
Suggestion: Mention that there is a Xcode 6.3 branch in README :)

### ISSUE THREAD

**Issue by Sajjon** [robb/Cartography#108]
The project does not build under Xcode 6.3 using cocoapods, but there is a branch that fixes this.

Please use this pod spettings in order to get it to work with XCode 6.3:
```ruby
pod 'Cartography', :git => 'https://github.com/robb/Cartography.git', :branch => 'xcode6-3'
```

Otherwise you will get error in file 'ConstraintGroup' something about "missing label 'combine'".

Thanks!

**Comment by aral** [comment]
Thanks for the tip :)

**Comment by robb** [comment]
That took care of itself :v:
