### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by VincentWenShuo** [robb/Cartography#110]
weak var weakIntroView = UIView()
        weak var weakView = UIView()
        
        constrain(weakIntroView!, weakView!) { weakIntroView, view in
            weakIntroView.center == view.center
            weakIntroView.width == view.width
            weakIntroView.height == view.height
        }

After calling the constrain function, the memory allocation for the two UIView are never cleared.
Any suggestion to fix this? Thanks a lot

**Comment by robb** [comment]
Can you confirm this is not related to #105?

**Comment by VincentWenShuo** [comment]
Thanks for reply. I tried with the latest code, it is still the same.

Maybe LayoutProxy is keeping the strong reference to the passed in view.

Cheers

**Comment by robb** [comment]
@VincentWenShuo can you try `master` now?

**Comment by VincentWenShuo** [comment]
Yes, it is fixed now. Thanks a lot.
