### ISSUE TITLE
unresolved identifier 'layout' - can't figure out the problem..

### ISSUE THREAD

**Issue by mortenholmgaard** [robb/Cartography#113]
I get this compile error all the time: 
> use of unresolved identifier 'layout'

I use it here:
    override func viewDidLoad() {
        super.viewDidLoad()
        layout(contentView) { contentView1 in
            contentView1.leading = contentView1.superview!.leading
            contentView1.trailing = contentView1.superview!.trailing
        }
    }

with this pods import:
    platform :ios, '8.0' 
    use_frameworks!
    pod 'Cartography', '~> 0.4.0'

Do you see a problem? It should be easy with a global method like this..

**Comment by robb** [comment]
Are you importing Cartography?

**Comment by mortenholmgaard** [comment]
Yes that was the problem - but I have tried to it do it but I didn't seem to exist..

**Comment by guibury** [comment]
I had this issue after import.
Just change the **layout(contentView) { contentView1 in** to **constrain(contentView) { contentView1 in**
