### ISSUE TITLE
Typealias issue in test target

### ISSUE THREAD

**Issue by hermanolsson** [robb/Cartography#114]
Hey, I'm not sure if this is by design or not, but there is a typealias issue occurring only in our test target.

View.swift
```
#if os(iOS)
    import UIKit
    public typealias View = UIView
    ...
```

ViewUtils.swift
```
#if os(iOS) && TEST
    import UIKit
    typealias View = UIView
#elseif TEST
...
```
The compiler error is 'Invalid redeclaration of 'View''. I cannot really tell how Cartography reacts, but removing the one in ViewUtils seem to fix the problem.

Note: We are using the Cartography source since we still need to support iOS 7.

**Comment by robb** [comment]
It's there to make testing ViewUtils easier, but you might want to upgrade to at least `Cartography 0.3.0`, which should work.

I'm probably going to remove the tests for `ViewUtils` rather than exposing them this awkwardly.

**Comment by hermanolsson** [comment]
Thanks, I'll give it a try.
