### ISSUE TITLE
SQLite Collision

### ISSUE THREAD

**Issue by sktaylor** [robb/Cartography#119]
`Number`, and `Expression` are both used in https://github.com/stephencelis/SQLite.swift.

I have to support iOS 7 so I can't bring the code in as a framework. I have a set of patches the changes `Number` to `CartographyNumber`, and `Expression` to `CartographyExpression`, so that the libraries play nice. It's easier to change cartography because the changes are all internal, they don't interact with the interface, unlike SQLite, where you actually use `Expression` in your code.

Would you be interested in merging them in? I wanted to ask before I go through the trouble of doing a fork / pull request.

Thanks for a great library.

- Kendrick

**Comment by robb** [comment]
> Would you be interested in merging them in?

Not really :grimacing: I don't really support iOS 7 nor static libraries. Maybe there's a way for you to automate the search and replace process so pulling in changes from upstream is easier?

Best of luck!

**Comment by sktaylor** [comment]
Makes my life easier. You might want to remove the part in the docs that says "file bug reports about name collisions."

**Comment by eholshouser** [comment]
In my opinion it should be considered a bug for any library to use names like that without a prefix, regardless of whether it has actually been observed to collide with anything in the wild.

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html

**Comment by robb** [comment]
@eholshouser This is only a problem where people need to manually bring in Cartography and e.g. that SQLite wrapper into the same namespace.

Swift has proper namespaces (at last) so this is really just a short time inconvenience until people can drop iOS 7 support. Since Cartography is a pure Swift framework that can't even be used from Objective-C files, it doesn't need to be bogged down by Objective-C conventions.

**Comment by eholshouser** [comment]
Yeah, I somehow briefly forgot that this was a Swift framework and deleted my comment shortly afterwards when I realized my mistake. Sorry for the misunderstanding.

**Comment by robb** [comment]
@eholshouser no worries :green_heart:
