### ISSUE TITLE
Docs using jazzy, gh-pages

### ISSUE THREAD

**Issue by jessesquires** [robb/Cartography#126]
Hi @robb !

I wanted to ask if you'd be interested in using [gh-pages](https://pages.github.com) to host docs generated by [jazzy](https://github.com/realm/jazzy), and willing to accept a PR with scripts to help automate that process?

Given the "growing pains" with [CocoaDocs](http://cocoadocs.org) + Swift, this is the approach I've started using in my own projects. It's easy to setup, and I've found it pretty painless to maintain.

Example: [JSQNotificationObserverKit](https://github.com/jessesquires/JSQNotificationObserverKit) and [docs](http://www.jessesquires.com/JSQNotificationObserverKit).

**Comment by robb** [comment]
Sounds interesting, thanks for offering to help :sparkling_heart: 

Do you think it's possible to have this happen exclusively in the `gh-pages` branch? The idea being that `gh-pages` includes `master` as a submodule and generates the docs from that.

**Comment by jessesquires** [comment]
I think that should be possible. As the owner, you would need to create the `gh-pages` branch, then I could submit a PR there

**Comment by zwaldowski** [comment]
`gh-pages` can indeed exist with its own separate history, great for deploying docsets.

**Comment by robb** [comment]
[The branch exists now](https://github.com/robb/Cartography/tree/gh-pages).
