### ISSUE TITLE
How to add Cartography with Carthage

### ISSUE THREAD

**Issue by crazylinuxsir** [robb/Cartography#130]
How to add Cartography with Carthage,what i need to write in my Cartfile

like Alamofire i just need write  "github "Alamofire/Alamofire" >= 1.2"

but i  can't find something like that  in your README.md

our production really need you fantastic job  :)

**Comment by robb** [comment]
Just add

```Cartfile
github "robb/Cartography" ~> 0.5
```

and you should be good to go :ok_hand:
