### ISSUE TITLE
Layout in the subview

### ISSUE THREAD

**Issue by AarongZhang** [robb/Cartography#131]
I have a question. I’m sorry about my poor english.
When I layout my controls in a view controller, the effect is right.
But when I put my all controls in a view(e.g. signInView), and add view in the view controller, then layout.  It makes some errors.

In the reveal, i found the repeat constraints.

![_2015-05-29_22 11 33](https://cloud.githubusercontent.com/assets/8254443/7895149/52ce3db8-06b0-11e5-97eb-e4af823ba2c5.png)
When i put a UITextField in the view, and layout it. it occurs errors.
![5753427b-e853-4872-b73d-38147861577f](https://cloud.githubusercontent.com/assets/8254443/7895150/5aa5d758-06b0-11e5-9618-df2148733a7a.png)
if set right constraint, it will be error.

sample code:

SignInView
![2015-05-30 10 36 18](https://cloud.githubusercontent.com/assets/8254443/7895302/deed2bfe-06b7-11e5-8d2a-e1d4e8cba1d7.png)

ViewController
![2015-05-30 10 36 29](https://cloud.githubusercontent.com/assets/8254443/7895303/e43954c0-06b7-11e5-89ec-460a536752a7.png)

Errors:

![2015-05-30 10 36 38](https://cloud.githubusercontent.com/assets/8254443/7895309/106c3df0-06b8-11e5-9995-c2d1955a0fb0.png)

**Comment by robb** [comment]
This being screenshots makes it a little hard on commenting on specific parts of the code.

Have you tried performing your `layout` call [`-updateConstraints`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/index.html#//apple_ref/occ/instm/UIView/updateConstraints) and overriding [`+requiresConstraintBasedLayout](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/index.html#//apple_ref/occ/clm/UIView/requiresConstraintBasedLayout) to return `true`?

**Comment by AarongZhang** [comment]
I tried it, and fixed it. Thanks!!!!
