### ISSUE TITLE
Swift 2.0 Support

### ISSUE THREAD

**Issue by derrh** [robb/Cartography#134]
@robb, Cartography is great. Thank you! I've forked it and refactored to add support for Swift 2.0. I've tried to maintain API compatibility, which means adding lots of `_`s. Tests are all passing. I didn't create a pull request, didn't seem like something that you would want on any of the current branches. So here it is: https://github.com/derrh/Cartography/tree/swift-2.0

**Comment by robb** [comment]
Thanks. :sparkling_heart: 

I pushed it to the [swift-2.0](https://github.com/robb/Cartography/tree/swift-2.0) branch on this repo. Feel free to target further PRs at that branch if anythings needs tweaking.

**Comment by 3webbg** [comment]
I can not find swift-2.0 branch?

**Comment by robb** [comment]
@3webbg It's been merged into `master` :sparkles:
