### ISSUE TITLE
Any wrong?

### ISSUE THREAD

**Issue by SoonKong** [robb/Cartography#151]
[!] The platform of the target `MyProject` (iOS 7.0) may not be compatible with `Cartography (0.5.0)` which has a minimum requirement of iOS 8.0 - OS X 10.9.

**Comment by SoonKong** [comment]
But I can use in ios 7, is there any wrong?

**Comment by robb** [comment]
iOS 7 is not officially supported by Cartography, so while I think you can make it work by e.g. copying all files into your project, it's really not something I can help you with, sorry.
