### ISSUE TITLE
Can I replace a group with another one

### ISSUE THREAD

**Issue by tyregor** [robb/Cartography#152]
Hi,

I'm very new to cartography and I really like the readable style that it introduces to constraints. 
My question is if its possible to replace one group with another group. What I mean is, that I create two ConstraintGroups-variables and initialize them with the constraints I need for two states of a simple view. At runtime I'd like to be able to apply these groups dynamically and switch between them. Is that possible or do I always have to repeat the closure-part of the constrain- and layout-functions?

Regards

**Comment by robb** [comment]
You can use the `active` property which should really be documented better :sweat_smile:

**Comment by tyregor** [comment]
Perfect! Exactly what I was looking for. Thx
