### ISSUE TITLE
Is it possible to get the current ConstraintGroup for a view?

### ISSUE THREAD

**Issue by haaakon** [robb/Cartography#153]
I have set

```swift
var group = constrain(self.view, newView ) { firstView, secondView in
    secondView.left == firstView.right
    secondView.width == firstView.width
    secondView.top == firstView.top
    secondView.bottom == firstView.bottom
}
```

Later in the app i want to replace these constraints. Do i have to store the reference to group myself, or is it possible to get this, as long as i have a reference to both views. 

Seems kind of messy to store references to groups everywhere i have set constraints that i might want to change at a later point.

**Comment by robb** [comment]
Unfortunately, I don't think there is a way to do this without storing a reference to the groups. If you made another call to `constrain`, Cartography couldn't really figure out reliably which constraints to replace.

**Comment by haaakon** [comment]
Allright. I'll store them then. Thanks for quick reply & making the best framework for working with constraints!

**Comment by robb** [comment]
Always happy to help.
