### ISSUE TITLE
Using variable from the class inside the closure 

### ISSUE THREAD

**Issue by mineschan** [robb/Cartography#154]
Hi, 

First of all, I like this library and i'm using it in my new swift projects happily, thanks for the contribution.

However, I come to a point that I'll have some class variable store the "default" element height, let say

```
    let viewHeight = 1000
```

But in Cartography examples I can't find a demo to use this kind of variable inside the layout closure, is there any way or how should I handle this kind of settings?

Thanks a lot, hope someone would answer me.

MineS

**Comment by robb** [comment]
That should work, as long as the variable is of `CGFloat`. Are you seeing any error messages on your end?

**Comment by mineschan** [comment]
OMG @robb you're awesome!
Yeh, I changed the variable a bit to ```let viewHeight:CGFloat = 1000``` and it works like a charm!

Thanks for your rapid reply, love Cartography even more now ;)

**Comment by robb** [comment]
Happy to help :v:
