### ISSUE TITLE
Code Signing issues with Cartography swift-2.0 branch

### ISSUE THREAD

**Issue by alvivi** [robb/Cartography#158]
Hello, I'm having issues trying to build Cartography swift-2.0 with Carthage. The output is:

```
** BUILD SUCCEEDED **

*** Building scheme "Cartography-iOS" in Cartography.xcodeproj
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator9.0

=== BUILD TARGET Cartography-iOS OF PROJECT Cartography WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos9.0

=== BUILD TARGET Cartography-iOS OF PROJECT Cartography WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **
```
I have a proper signing identity, and all other carthage dependencies are working properly. Even Carthage master works. Any ideas?

**Comment by nyc** [comment]
I had a similar code-signing issue and after looking at [this issue](https://github.com/Carthage/Carthage/issues/283), I realized that I didn't have an `iPhone Distribution` certificate set up. To do so, go to 
```
Preferences > Accounts > View Details > Signing Identities > iOS Distribution > Create
```
This fixed it for me and Cartography is building properly. @robb I don't think this is an actual issue with the library.

**Comment by alvivi** [comment]
@nyc, Thank you. Adding an account distribution certificate fixes the problema.

**Comment by robb** [comment]
Cool :v:
