### ISSUE TITLE
(unexpected file type 'wrapper.pb-project' in Frameworks & Libraries build phase)

### ISSUE THREAD

**Issue by wratke** [robb/Cartography#164]
I'm trying to update Cartography after updating a project to use Xcode 7 and Swift 2, but I'm getting this error message after adding the framework and trying to build the project:

warning: skipping file '/Cartography-master/Cartography.xcodeproj' (unexpected file type 'wrapper.pb-project' in Frameworks & Libraries build phase)

I've removed the old version as far as I can tell. I'm adding it by dragging the Cartography.xcodeproj into Xcode and then adding it into the General>Embedded Binaries section of the project's Target options. Am I missing something, or is it just not working with Xcode at the moment?

**Comment by robb** [comment]
That's not quite how that's supposed to work. You need to add Cartography to the workspace and drag the framework product into the Embedded Binaries section, not the project itself.

I would recommend Carthage to simplify this process though.

**Comment by robb** [comment]
Feel free to reopen this if you have any further questions :smile_cat:
