### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by orkhanalizade** [robb/Cartography#169]
```
dyld: Library not loaded: @rpath/Cartography.framework/Cartography
Referenced from: /var/mobile/Containers/Bundle/Application/F6522157-398D-4800-8130-91BFF616969F/Linguist.app/Linguist
Reason: image not found
```

How to fix it?

**Comment by robb** [comment]
You probably need to embed the binaries, please refer to the [Carthage instructions](https://github.com/Carthage/Carthage#getting-started).

**Comment by orkhanalizade** [comment]
@robb I use Podfile, not Cartfile and I cannot to add your framework to Embed Binaries. Why you closed an issue? It didn't solve my problem =/

**Comment by robb** [comment]
Sorry for the terse reply. :bow: Unfortunately, I'm not sure what the cause of your problem is, can you post more information about your workspace/Podfile/etc.?

**Comment by orkhanalizade** [comment]
My podfile content is:

    use_frameworks!
    pod 'performSelector-swift'
    pod 'UIColor+FlatColors'
    pod 'Cartography'
    pod 'ReactiveUI'

When I compile it in my simulator, it works perfectly, but when I try to run it on my iPhone, it crashes, that `Reason: image not found`

**Comment by orkhanalizade** [comment]
@robb  did you find any solutions for this issue?

**Comment by robb** [comment]
It does sound like your workspace is misconfigured and the Cartography framework is not copied when you build it for your device. Are those `DEBUG` builds?

I'm not using Cocoapods myself for Swift stuff, so I'm just stabbing in the dark here.

**Comment by cobear25** [comment]
Same thing is happening for me.

**Comment by fiveze** [comment]
+

**Comment by orta** [comment]
Please don't +1, provide a useful example so people can help you in a new issue.
