### ISSUE TITLE
Cannot pass more than 5 parameters in constrain

### ISSUE THREAD

**Issue by Daemon-Devarshi** [robb/Cartography#170]
If I use this then it works fine:
```
constrain(userProfileView, lastName, streetAddress1, streetAddress2, city) {parent, lastName, streetAddress1, streetAddress2, city in
            //some autolayout constraints added
        }
```
but if I add one more parameter like this:
```
constrain(userProfileView, lastName, streetAddress1, streetAddress2, city, zip) {parent, lastName, streetAddress1, streetAddress2, city, zip in
            //some autolayout constraints added
        }
```

Compiler starts complaining with this error:

`Cannot invoke 'constrain' with an argument of type (_, _, _,_, _, _) -> _`

Any ideas?

**Comment by hermanolsson** [comment]
constrain takes a maximum of 5 views, but there is an overload taking an array of views you probably can use.

If each of the views don't have a relation to all other views, consider splitting them up into multiple constrain blocks.

**Comment by robb** [comment]
Yup, that's the idea. You can also create your wrapper around the `constrain(views: [View])` overload that takes however many views you like.

**Comment by codeOfRobin** [comment]
@robb Couldn't you also use ![variadic parameters](http://stackoverflow.com/questions/24124956/variadic-parameters-and-defaulted-parameters) to do something like this?
