### ISSUE TITLE
Unable to simultaneously satisfy constraints

### ISSUE THREAD

**Issue by wratke** [robb/Cartography#173]
I'm trying to replace a constraint and animate it using the code in the wiki as an example, but I'm getting the "Unable to simultaneously satisfy constraints" error. I'm not sure what I'm doing wrong, everything looks the same as the example:

```swift
constrain(self.coin, self.slot) { coin, slot in
     coin.centerX == slot.centerX
     coin.bottom == slot.top - 10
}
        
self.coinConstraint = ConstraintGroup()
```

later in the code I replace the constrain and animate it using this code:

```swift
constrain(self.coin, self.slot, replace: self.coinConstraint) { coin, slot in
     coin.bottom == slot.top + 500
}
            
UIView.animateWithDuration(0.5, animations: self.coin.layoutIfNeeded)
```

The error code in Xcode makes it look like the constraint isn't actually being replaced:

```
"<NSLayoutConstraint:0x18272f40 TonicTutor.PigCoin:0x16e18950.bottom == UIImageView:0x16d113e0.top - 10>",
    "<NSLayoutConstraint:0x16e1a220 TonicTutor.PigCoin:0x16e18950.bottom == UIImageView:0x16d113e0.top + 500>"
```

Am I missing something?

**Comment by wratke** [comment]
Error code I copied and pasted didn't post, going to try that again:

<NSLayoutConstraint:0x18272f40 TonicTutor.PigCoin:0x16e18950.bottom == UIImageView:0x16d113e0.top - 10>,
<NSLayoutConstraint:0x16e1a220 TonicTutor.PigCoin:0x16e18950.bottom == UIImageView:0x16d113e0.top + 500>

**Comment by wratke** [comment]
NSLayoutConstraint:0x18272f40 TonicTutor.PigCoin:0x16e18950.bottom == UIImageView:0x16d113e0.top - 10

NSLayoutConstraint:0x16e1a220 TonicTutor.PigCoin:0x16e18950.bottom == UIImageView:0x16d113e0.top + 500

**Comment by robb** [comment]
You need to capture the first set of constraints, not create an empty `ConstraintGroup`, e.g.:

```swift
self.coinConstraint = constrain(self.coin, self.slot) { coin, slot in
     coin.centerX == slot.centerX
     coin.bottom == slot.top - 10
}
```

**Comment by wratke** [comment]
That definitely makes sense. I think it would be helpful to update the wiki since it's not immediately clear that you need to capture the constraint group in the variable, it looks like it captures the constrain directly preceding it.
