### ISSUE TITLE
How to add two heights together?

### ISSUE THREAD

**Issue by drosenstark** [robb/Cartography#207]
I'm trying to sum heights like this: `outerView.height == label1.height + label2.height` but I get this error: 

    Binary operator '+' cannot be applied to two 'Dimension' operands

Is there any way to add two heights together? 

Thank you!

----
**Note:** I'm trying to make an enclosing view shrink to the heights of the two automatically-sized labels it contains. Perhaps there's another way to do this entirely.

**Comment by robb** [comment]
You could attach the outer `top` to the `top` of the upper label and the same for the `bottom` of the other label.

**Comment by drosenstark** [comment]
Got to delete a lot of code thanks to this response, which is, for me, the most exciting thing in writing code. Also managed to figure out my autolayout conflicts. 

Thank you!
