### ISSUE TITLE
Swift 3.0 compatible branch

### ISSUE THREAD

**Issue by mluisbrown** [robb/Cartography#216]
I know it's very early days, but any idea when a branch migrated to Swift 3 will be available? Anyone depending on this lib (or any other Swift libs) is currently stuck not being able to build their projects with Xcode 8 until all dependent libs are also migrated to Swift 2.3 or 3.0 (preferable).

**Comment by solomon23** [comment]
I've created this fork that should get you at least to compile: 
https://github.com/solomon23/Cartography/tree/3.0

or via pods

pod 'Cartography', :git => 'https://github.com/solomon23/Cartography.git', :branch => '3.0'

**Comment by mluisbrown** [comment]
Thanks @solomon23. It compiles and, at least in my usage of it, also works fine! 👍

**Comment by CVertex** [comment]
@solomon23 nice!

**Comment by GP000** [comment]
![1](https://cloud.githubusercontent.com/assets/22322197/18671770/0de25096-7f4e-11e6-9599-66984e431609.png)

I have have problem with converting to the latest Swift 3 syntax

I use "pod 'Cartography', :git => 'https://github.com/solomon23/Cartography.git', :branch => '3.0'" to install Cartography

**Comment by mluisbrown** [comment]
Hi @GP000 looks like that fork hasn't been updated to the latest Swift 3.0 syntax. Try my fork instead, which I'm using in a shipping app: 

`pod 'Cartography', :git => 'https://github.com/mluisbrown/Cartography.git', :branch => 'swift3'`

I haven't tried using it with CocoaPods (I use Carthage) but it should be fine.

**Comment by mluisbrown** [comment]
Sorry, closed the issue by mistake :blush: . Re-opened.

**Comment by mluisbrown** [comment]
Just looking at your screenshot more, I can't see the full error but it looks like it's saying `Unknown attribute 'discardableResult'` . If that's the case then maybe your project is not using Swift 3.0? That is a new attribute introduced in Swift 3.0.

**Comment by orta** [comment]
There is an active PR for 3.0 #228 would recommend using that instead

**Comment by GP000** [comment]
![2](https://cloud.githubusercontent.com/assets/22322197/18673716/7d426f64-7f55-11e6-8e38-4289b4308be3.png)

after conversion to the latest syntax passed the following errors appeared

**Comment by GP000** [comment]
it is an empty project with only Cartography imported via pods

**Comment by orta** [comment]
Swift 3.0 support is now in 1.0 💯

**Comment by blackphnx** [comment]
When I import cartography onto my project I get this error.

 Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: /Carthage/Build/iOS/Cartography.framework/Modules/Cartography.swiftmodule/arm64.swiftmodule

**Comment by orta** [comment]
Yep - binaries only work on a specific version of Swift. Any minor swift changes requires a new binary.
