### ISSUE TITLE
Swift3, XCode 8.0 beta3

### ISSUE THREAD

**Issue by alexiosdev** [robb/Cartography#224]
Hey, guys.
Please check this link. It's just for Xcode 8.0 beta 3
https://github.com/alexiosdev/Cartography/tree/swift3_alex

**Comment by rodrigoruiz** [comment]
So, when is this going to be merged into the main one?

**Comment by orta** [comment]
funny, I was just working on this - https://github.com/raphaelcruzeiro/Cartography/pull/1

**Comment by rodrigoruiz** [comment]
Somehow it's now downloading the same source code as the one on the repo when I do `pod 'Cartography', :git => 'https://github.com/alexiosdev/Cartography.git'`

**Comment by NeuralGlue** [comment]
You may not be including the tag for the Swift3 project. It you're wanting to use alexoisdev's work try this in your pod file:

>     pod 'Cartography', :git => 'https://github.com/alexiosdev/Cartography.git',  :branch => 'swift3_alex'

**Comment by atomic-avocado** [comment]
@orta has just released a new branch for swift3 ... haven't tested it yet tho... plan on doing it during the weekend. Anyway.. Thanks for the effort Orta 👍 
https://github.com/robb/Cartography/tree/swift3_ci

**Comment by orta** [comment]
No credit to me - it's all @raphaelcruzeiro's work - I'm just getting the CI working

**Comment by orta** [comment]
Swift 3.0 support is now in 1.0.0 💯
