### ISSUE TITLE
Assign value from variable

### ISSUE THREAD

**Issue by originell** [robb/Cartography#230]
Probably I am just not going about this the right way:

```
let imgHeight = apiData.bgImage.height  // 80.0
constrain(self.imgView) { view in
    view.height == imgHeight
}
```

Leads to

> Cannot convert value of type 'Dimension' to expected argument type 'Int'

Is there a way to make this work? If not I'll just fallback to a regular `NSLayoutConstraint`. Would be great if one could make this work though :)

**Comment by robb** [comment]
What type is `height`?

**Comment by originell** [comment]
in this case it's already an `Int` . That's also why the error message confuses me.

You should be able to reproduce this pretty easily, at least with XCode 7. Didn't try it with 8b for now.

**Comment by robb** [comment]
Oh, nevermind, it tries to convert the lhs `Dimension` to `Int` (which it can't). Try casting e.g. `view.height == Doule(imgHeight)`?

**Comment by originell** [comment]
Ah. Now we have a different error :)

```
let imgHeight = apiData.bgImage.height  // 80.0
constrain(self.imgView) { view in
    view.height == Double(imgHeight)
}
```

Leads to

> Ambiguous reference to member '=='

**Comment by turekj** [comment]
I stumbled upon similar problem yesterday. I could not multiply height by a `ratio` variable:

```
let ratio = 0.45

constrain(self.entryView) { v in
    v.height == v.superview!.height * ratio
}
```

Figured it out looking at Coefficients.swift:

```
public func * (m: CGFloat, rhs: Coefficients) -> Coefficients {
    return Coefficients(rhs.multiplier * m, rhs.constant * m)
}

public func * (lhs: Coefficients, rhs: CGFloat) -> Coefficients {
    return rhs * lhs
}
```

Since multiplier should be defined as CGFloat, I did the following:

```
let ratio = 0.45 as CGFloat

constrain(self.entryView) { v in
    v.height == v.superview!.height * ratio
}
```

I guess it fix your problem too. I just did a quick test and below solution works:

```
let imgHeight = apiData.bgImage.height as CGFloat
constrain(self.imgView) { view in
    view.height == imgHeight
}
```

Hope it helps :)

**Comment by originell** [comment]
yep indeed this works. Thanks a lot @turekj  :)!
