### ISSUE TITLE
Release 0.7 not available on Cocoapods

### ISSUE THREAD

**Issue by sparga** [robb/Cartography#233]
It seems that the latest release (and the 0.6) has not been published on Cocoapods.
I am migrating a project to Swift 2.3 and the only way to do it is to use the Git tag, which is not very clean 😬 

Thanks

**Comment by Douvi** [comment]
Currently you can do this 

```
pod 'Cartography', :git => 'git@github.com:robb/Cartography.git', :tag => '0.7.0'
```

**Comment by sparga** [comment]
Thank you, that's what I am already doing but then you loose the versioning benefits of Cocoapods.
Is there a specific reason why this release is not published on the Cocoapods repo?

**Comment by vfn** [comment]
The podspec has not been updated with the correct version number. It is stuck on version 0.5.0. I'm not sure if it has any effect on how cocoapods work.

**Comment by orta** [comment]
You should be fine to use 0.7.0 on trunk now
