### ISSUE TITLE
error: cannot invoke 'constrain' with an argument list of type 

### ISSUE THREAD

**Issue by samkhawse** [robb/Cartography#243]
I'm using **Cartography 0.7** and **Swift 2.3/XCode7.3** with _Carthage_ and I get the following error when I use the `constrain` method on two views

```
MyViewController.swift:44:9: error: cannot invoke 'constrain' with an argument list of type '(UITableView!, UITabBarItem!, (_, _) -> _)'
        constrain(tracksTableView, tabBarItem) { (view1, view2) in
        ^
MyViewController.swift:44:9: note: expected an argument list of type '(View, View, replace: ConstraintGroup, block: @noescape (LayoutProxy, LayoutProxy) -> ())'
        constrain(tracksTableView, tabBarItem) { (view1, view2) in
```

`constrain` works fine if used only on 1 view like 

```
constrain(tableView) { view in 
    view.top == view.superview.top
}
```

Does anyone know why it's trying to look for `(View, View, replace: ConstraintGroup, block: @noescape (LayoutProxy, LayoutProxy) -> ())`?

**Comment by vfn** [comment]
@samkhawse `UITabBarItem` is not a subclass of `UIView`.

https://developer.apple.com/reference/uikit/uitabbaritem
