### ISSUE TITLE
Memory Leak in "specialized closestCommonAncestor(UIView, b : UIView) -> UIView?"

### ISSUE THREAD

**Issue by 577528249** [robb/Cartography#246]
my xcode version is 8.1, my project is based in swift 2.3, 
![image](https://cloud.githubusercontent.com/assets/16741621/20957168/265fe700-bc89-11e6-9358-30836acc4ee7.png)
![image](https://cloud.githubusercontent.com/assets/16741621/20957251/95d18ef4-bc89-11e6-9642-33059e0a9c46.png)
![image](https://cloud.githubusercontent.com/assets/16741621/20957216/5a9812d6-bc89-11e6-9b4c-18f498d8c411.png)
![image](https://cloud.githubusercontent.com/assets/16741621/20957228/759771bc-bc89-11e6-8287-d0bfc8fe1128.png)
![image](https://cloud.githubusercontent.com/assets/16741621/20957236/822790ec-bc89-11e6-8156-f5fe1c8b05b3.png)

**Comment by orta** [comment]
Cool, want to try send a PR to fix it for everyone?

**Comment by 577528249** [comment]
Wow! That‘s cool, I want to try this, Thanks!

**Comment by 577528249** [comment]
Hello,I'm sorry for the issue , because my project use Carthage to manage the library,which real cause Cartography，Alamofire，Charts memory leak in my project.So it not Cartography cause the problem. I'm sorry for what I say before,I will more cautious in next time. Thanks!
