### ISSUE TITLE
Update code for Swift 4 iOS 11

### ISSUE THREAD

**Issue by DrewKiino** [robb/Cartography#261]
hey, we use this library in one of our flagship apps and it seems that auto layout has been changed in iOS 11 such as button's frames not being set. iOS 11 comes out in a couple of months or so, so just a heads up because we love this pod and would love to use it once XCode 9 comes out.

**Comment by orta** [comment]
Sure, want to look at doing it?

**Comment by tzm41** [comment]
iOS 11 comes out next Tuesday

**Comment by orta** [comment]
Someone else did it, https://github.com/robb/Cartography/pull/262
