### ISSUE TITLE
Add safeAreaLayoutGuide support

### ISSUE THREAD

**Issue by NachoSoto** [robb/Cartography#265]
Similar to #203, it would be great to support `UIView.safeAreaLayoutGuide`. What's even better with this is that it's exposed on `UIView`, not `UIViewController`, so we wouldn't need to couple that anymore!

**Comment by inamiy** [comment]
See Also: #267

**Comment by NachoSoto** [comment]
So I was about to close this since it got done in #267, but I just posted a question in #269 cause I think the support became worse?

**Comment by NachoSoto** [comment]
See my response there, this works great!
