### ISSUE TITLE
UILayoutPriority is no longer a number, it is a RawRepresentable

### ISSUE THREAD

**Issue by philippelatulippe** [robb/Cartography#270]
After updating to Swift 4, the priority operator `~` no longer works with doubles and integers, since UILayoutPriority is a RawRepresentable now. This breaks many constraints defined using Cartography, and requires writing this unwieldy kind of constraint `view.bottom == sv.bottom ~ LayoutPriority(rawValue: 900.0)`.

It would be great if ` func ~` accepted integers and doubles in order to work around this.

**Comment by philippelatulippe** [comment]
I've submitted a PR that adds this: https://github.com/robb/Cartography/pull/271

**Comment by NachoSoto** [comment]
This can be closed now? :)

**Comment by orta** [comment]
Yep 👍
