### ISSUE TITLE
 Consider to bring back topLayoutGuideCartography and bottomLayoutGuideCartography

### ISSUE THREAD

**Issue by khanhshopback** [robb/Cartography#287]
I was using those two edges, but look like they were removed after I upgraded to 3.0.1
Can we bring them back? Or any reason why you removed it?

**Comment by corujautx** [comment]
It was removed because Cartography now supports constraining `UILayoutSupport`s and `UILayoutGuide`s by using the `constrain` function.

Consider replacing your code where `topLayoutGuideCartography` to something akin to:

```swift
constrain(view, self.topLayoutGuide) { view, topLayoutGuide in 
    view.top == topLayoutGuide.bottom
}
```

**Comment by khanhshopback** [comment]
I see. Thank @corujautx
