### ISSUE TITLE
Publish v3.1.0 to Cocoapods?

### ISSUE THREAD

**Issue by sebastianv1** [robb/Cartography#305]
I see a tag for 3.1.0, but this hasn't been bumped in the podspec nor published. 3.1.0 has swift 4.2 support, is there any plan to publish this version soon?

**Comment by micnguyen** [comment]
I think there may be a mistake with the podspec version published as 4.1.0
https://github.com/robb/Cartography/commit/f29fd89769ee5fb03f80c28fda72866c45e985a3

**Comment by micnguyen** [comment]
It looks to be there? I've just tried it and it works with Swift 4.2
https://github.com/CocoaPods/Specs/blob/master/Specs/9/9/2/Cartography/3.1.0/Cartography.podspec.json
