### ISSUE TITLE
Question: Is this project still active?

### ISSUE THREAD

**Issue by dcordero** [robb/Cartography#329]
I see that the last version was released more than 2 years ago and the last commit to the master branch is from 14 months ago.

Based on that, I wonder if this project is still active or I should consider using it from now on.

Could you help me to clarify if my concerns make any sense?

Thanks a lot.

**Comment by orta** [comment]
I merge green PRs and occasionally make releases, but I don't do any active work to improve this lib

**Comment by dcordero** [comment]
I see, thanks a lot for clarifying @orta.

And of course thanks a lot for creating and sharing this great project.
