### ISSUE TITLE
Use of unresolved identifier 'layout'

### ISSUE THREAD

**Issue by ratkins** [robb/Cartography#39]
Cartography is the first third party framework I've tried using in my Swift project. I'm having difficulty with the installation process. So far I have:
- Cloned the Cartography git repository onto my local machine
- Worked out that you have to "Archive" (rather than "Build") to get Xcode to build something, and that you have to select "iOS Device" before "Archive" becomes selectable
- Built and archived
- Found the actual `Cartography.framework` bundle in the uncharted depths of my filesystem
- Copied the `Cartography.framework` bundle into my project
- Added `Cartography.framework` to the "Link Binary With Libraries" build phase of my target
- Added `import Cartography` to the top of my Swift file where I wanted to use it

Now I'm getting the error `Use of unresolved identifier 'layout'` and I'm fresh out of ideas.

(It would be helpful to have the basic process in the README.md. I know most of it isn't specific to Cartography, but the procedures around this are so new and rapidly evolving it'd be helpful to have the basic known-working steps here.)

**Comment by dkrdennis** [comment]
I still got this issue. 

After a import to Xcode of all the files in the Cartography i get the error: ´´´ Use of unresolved identifier 'layout' ´´´And I have no idea how to solve this problem. 

Anyone have a walkthrough to use Cartography in your iOS project supporting iOS 7

**Comment by guibury** [comment]
change the **layout(tableView) {** to **constrain(tableView) {**
