### ISSUE TITLE
Pass a dictionary with views instead of an array

### ISSUE THREAD

**Issue by wratke** [robb/Cartography#43]
Would it be possible to add support for dictionaries when passing an arbitrary number of views? Having the ability to create an array of views is great, but accessing the views using just an array index (e.g. views[0] and views[1]) makes the code a bit more unreadable. If we could access the views using a dictionary like this:

```swift
layout(["view1": view1, "view2": view2) { (views) -> () in
            views["view1"].width == (views["view1"])].superview!.width - 40)
            views["view1"].height == 50
}
```

It would make for more readable code that would be easier to maintain.

**Comment by devxoul** [comment]
It would be great if there is `NSDictionaryOfVariableBindings` macro in swift... I don't like to write `view1` again and again :p
