### ISSUE TITLE
"==" doesn't seem to support CGFloats

### ISSUE THREAD

**Issue by michaeleisel** [robb/Cartography#56]
I have function, call it f, which returns a CGFloat, and I want to do this:

```swift
layout(view) {
    view.width == f(); return
}
```

This won't work currently

**Comment by ngoccuong291** [comment]
Looks like I have the same issue:

```
        var margin = 15
        
        layout(productView) { view in
            view.left   == view.superview!.left + margin
            view.right   == view.superview!.right - margin
            view.top   == view.superview!.top + margin
            view.height == view.width
        }
```

**Comment by robb** [comment]
For the time being, you need to cast to `Float` like so:

```
var margin: Float = 15

layout(productView) { view in
    // …
}
```

**Comment by ngoccuong291** [comment]
@robb Looks like it's a good solution for the time being. Thanks

**Comment by CVertex** [comment]
@robb Would you ever consider adding CGFloat support? I started implementing this and realized it's not really worth it.. Thoughts?
