### ISSUE TITLE
Must be missing something

### ISSUE THREAD

**Issue by angelboom** [robb/Cartography#62]
Trying to learn Cartography but ran into the problem below at my first attempt.

        layout(profileImageView) { view in
            view.left == 8
        }

Compiler says: Could not find member "left"

**Comment by robb** [comment]
See #9

**Comment by robb** [comment]
Sorry for the terseness, was just about to head out. Thanks for filing the issue!

**Comment by angelboom** [comment]
Thanks for the help :-) Must've read the other issues first.
