### ISSUE TITLE
Fails in Extension to NSView

### ISSUE THREAD

**Issue by drosenstark** [robb/Cartography#66]
Example of an NSView Category:

```swift
extension NSView {
    func sizeToFillSuperview() {
        layout(self) { view in
            view.size == view.superview!.size; return
        }
    }
}
```

Swift Compiler Error is "extra argument in call"

Early substitution for self doesn't help, nor does anything else I've thought of.

Obviously a global function  like this is okay, but not ideal:

```swift
func sizeToFillSuperview(view: NSView) {
    layout(view) { box in
        box.size == box.superview!.size; return
    }
}
```

THANKS!

**Comment by robb** [comment]
Looks like `layout` is getting shadowed by `NSView.layout`, hadn't realized this.

This should do the trick:

```swift
func sizeToFillSuperview(view: NSView) {
    Cartography.layout(view) { box in
        box.size == box.superview!.size; return
    }
}
```

**Comment by drosenstark** [comment]
Ok, got it, thank you!

**Comment by drosenstark** [comment]
Hmmm... on the one hand, this is very simple. I must use Cartography as a separate .framework instead of including the sources directly in the Xcode project... 

On the other hand, I'll have to open up another ticket about all my issues getting Cartography to work as a framework, whether via CocoaPods or just grabbing the .framework directory and pulling it in (runtime errors).

Thanks for your time and this framework!
