### ISSUE TITLE
Passing Variables to Layouts

### ISSUE THREAD

**Issue by drosenstark** [robb/Cartography#67]
I'm trying to do this type of thing

        layout(splitView, boxStatus) { split, box in
            box.height == 31
            split.height == box.superview!.height - 31
            split.bottom == box.top
        }

which works, but I'd like to parameterize this so the 31 is a variable. (I'm not even able to use `box.height` in the second line.)  

Hints, please, or is this a limitation of the framework?

Thanks!

**Comment by robb** [comment]
you need to cast your variable to `Float`, as per #56. So

```swift
layout(splitView, boxStatus) { split, box in
    box.height == CGFloat(someVar)
    split.height == box.superview!.height - CGFloat(someVar)
    split.bottom == box.top
}
```

**Comment by drosenstark** [comment]
Wow, okay! I'm using `Float(someVar)` instead of `CGFloat` but it all works now. Thanks for responding (and for Cartography, again)!

**Comment by drosenstark** [comment]
Would be nice to have a FAQ instead of having to look through issues. Not sure if GitHub does that....
