### ISSUE TITLE
CGFloat is an undeclared type

### ISSUE THREAD

**Issue by tcurdt** [robb/Cartography#70]
I am not sure why but according to the Swift compiler `CGFloat` is an undeclared type - and I had to add `import UIKit` to that file to make it compile. 

https://github.com/robb/Cartography/blob/master/Cartography/Extensions.swift#L37

I am bit flabbergasted but it seems like it's not declared in Foundation. http://stackoverflow.com/questions/24700245/cgfloat-not-defined-in-foundation-framework

**Comment by robb** [comment]
Weird

Did you just build Cartography in Xcode or through Carthage or Cocoapods? What version of Xcode were you using?

**Comment by tcurdt** [comment]
CocoaPods (0.34.4) with Xcode 6.1 (6A1046a).
Downloading Xcode 6.1.1 as we speak.

**Comment by robb** [comment]
Yeah, I can replicate it in Xcode 6.1 (6A1052c), I'll push a fix but probably wouldn't bother to tag `0.2.1` if it's already fixed in Xcode 6.1.1
