### ISSUE TITLE
cannot build with cocoapods

### ISSUE THREAD

**Issue by tcurdt** [robb/Cartography#71]
Seems like I run into these

https://github.com/CocoaPods/CocoaPods/issues/2226
http://openradar.appspot.com/radar?id=5536341827780608

    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

**Comment by robb** [comment]
Yeah, you need [CocoaPods 0.36](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) for Swift and frameworks support. You were using 0.34.4, right?

**Comment by tcurdt** [comment]
Yup. I guess it's update time today then. Thanks.

**Comment by robb** [comment]
:ok_hand:
