### ISSUE TITLE
width and position based on superview

### ISSUE THREAD

**Issue by tcurdt** [robb/Cartography#73]
I tried

        self.button1.backgroundColor = UIColor.redColor()
        layout(self.button1) { view in

            view.left == view.superview!.width * 0.1
            view.width == view.superview!.width * 0.1

            view.top == view.superview!.height * 0.1
            view.height == view.superview!.height * 0.3
        }

but assigning `left` and `top` like that does not work. Shouldn't it?
Using a fix margin like this does work for the positioning:

        self.button1.backgroundColor = UIColor.redColor()
        layout(self.button1) { view in

            view.left == view.superview!.left + 20
            view.width == view.superview!.width * 0.1

            view.top == view.superview!.top + 20
            view.height == view.superview!.height * 0.3
        }

But it seems like it's ignoring the width and height and is still using the size given in IB.
I haven't dug deeper yet.

**Comment by robb** [comment]
`left` is just a point on the x axis whereas `width` is a length. You could imagine something like `a.left == b.left + c.width` but Auto Layout cannot express constraints with three variables, yet.

I haven't had much experience in mixing Cartography with IB but maybe a higher priority (which can be set with the `~` operator) would help?

**Comment by tcurdt** [comment]
Turning off AL for the view controller in IB did the trick.

With the `left` I am still not totally clear on how that is e.g. different from `view.centerX == view.superview!.centerX * 0.5` - which works.

**Comment by robb** [comment]
To me it's the other way round, I'm still surprised `view.centerX == view.superview!.centerX * 0.5` works and I don't find it very intuitive, either. (`view.centerX` will be halfway between `superview.left` and `superview.center`, right?)

Maybe it's just something Apple designers needed really badly so it was hacked in?

**Comment by robb** [comment]
Tentatively closing this once, since this is fundamentally an Auto Layout issue, but feel free to reopen if you have more questions.
