### ISSUE TITLE
A way to chain ==

### ISSUE THREAD

**Issue by mergesort** [robb/Cartography#77]
If I have a few views that are all going to have the same property, for example
```
button1.top == superview.top
button2.top == superview.top
```

It would be great to be able to chain those operations and say

```
button1.top == button2.top == superview.top
```
Currently it produces an error `Non-associative operator is adjacent to operator of same precedence`. I'm not sure if this is possible with Swift, but it would help me make the code a bit more streamlined.

**Comment by robb** [comment]
Yeah, `Non-associative operator is adjacent to operator of same precedence` is kind of a dealbreaker, I really don't want to override the associativity of `==`.

Also, it would complicate capturing constraints.

**Comment by robb** [comment]
There could be something like `alignTopEdges(view1, view2, view3)`, too, but I'm not sure what the syntax should be.

**Comment by robb** [comment]
I guess you could also have something like

```swift
layout(view1, view2, view3) { view1, view2, view3 in 
    combine(view1, view2, view3).top == view1.superview!.top
}
```

but that looks even more complicated

**Comment by mergesort** [comment]
Fair points. I think https://github.com/robb/Cartography/issues/77#issuecomment-73859870 might be too specific, but is closest to what I'd envision. There could be a function that takes in a set of views, and an edge/dimension/size.

```
layout(view1, view2, view3) {
    equal([view1, view2, view3], Edge.top) // or Dimension or size
}
```

**Comment by truppelito** [comment]
@mergesort Just my two cents: if you exchange the order of the arguments you can dispense with the square brackets by using variadic parameters `equal(Edge.top, view1, view2, view3)`. That's probably better?

**Comment by mergesort** [comment]
@truppelito Var args sound good to me.
