### ISSUE TITLE
Linking Cartography causes glitched rendering in Mac app

### ISSUE THREAD

**Issue by brow** [robb/Cartography#78]
Thanks for Cartography! I use it with gusto on iOS and would like to use it in my Mac project, but can't yet because of this issue.

1. Create a fresh Swift Mac app project in Xcode 6.1.1.

2. In the nib, add an NSTableView to the app's window.

  ![screen shot 2015-02-10 at 11 59 25 pm](https://cloud.githubusercontent.com/assets/238331/6143628/f1efff06-b180-11e4-9e73-f7a3dfa7faa3.png)

  You can build and run now, if you like. The window looks as expected:

  ![screen shot 2015-02-11 at 12 02 14 am](https://cloud.githubusercontent.com/assets/238331/6143648/45a272f0-b181-11e4-88f1-1b61a0d6aa9b.png)

3. Build Cartography 0.2 using Carthage and link it. Build and run the app again. Now it looks like this:

![screen shot 2015-02-11 at 12 03 36 am](https://cloud.githubusercontent.com/assets/238331/6143663/7429e1e4-b181-11e4-99dd-367ced9fd9dc.png)

Here's a project you can use to repro, with steps 1-3 as separate commits: https://github.com/brow/CartographyIssue

**Comment by robb** [comment]
Thanks for the example project :sparkling_heart: 

The issue was a file from the test target being assigned to the Mac framework target, should be fixed in `0.2.1`.

**Comment by brow** [comment]
Thank you! ✨🎸
