### ISSUE TITLE
Remove constraints of ConstraintGroup

### ISSUE THREAD

**Issue by truppelito** [robb/Cartography#81]
Let's imagine I create a ConstraintGroup `let group = constrain( ... ) { ... }` and I later want to remove all those constraints I added (but I don't want to replace them with anything else).

Is there an easy way to remove all constraints of a group?

Right now, the only thing I'm thinking of is `constrain(someRandomView, replace: group) { v in return }`, but that's not very elegant, and so not on par with the rest of Cartography :)

**Comment by truppelito** [comment]
By the way, in the case of the project that I'm working on I actually don't want to layout the views after removing the constraints (hence the `constrain` instead of `layout`), but I'm sure there will be need for both, so I'd suggest adding a method to ConstraintGroup like `uninstall(#layout: Bool)`. Pretty much what you already have with `replaceConstraints(constraints: [Constraint], performLayout: Bool)` except that `constraints` is an empty array.

**Comment by robb** [comment]
how about

```swift
constrain(clear: group)
```

and

```swift
layout(clear: group)
```

?

**Comment by truppelito** [comment]
That's perfectly fine with me.
