### ISSUE TITLE
Add "spaced out" method

### ISSUE THREAD

**Issue by robb** [robb/Cartography#85]
Equivalent to #84 

Something like

```swift
spacedOut(by: 10, horizontally: view1, view2, view3)
```

as shorthand for 

```
view1.right + 10 == view2.left
view2.right + 10 == view3.left
```

**Comment by robb** [comment]
Or maybe rather `distribute(by: 10, horizontally: view1, view2, view3)`?

**Comment by truppelito** [comment]
That sounds awesome! Great idea. Also, what about something akin to `dstribute` that automatically creates spacer views (and the right constraints) for when spaces between views should be the same? This is a pretty common pattern with auto-layout (at least for me).

For example: `distribute(by: .Equal, horizontally: view1, view2, view3)` would be equivalent to:

```
// Add spacers to superview
let spacer1 = UIView()
let spacer2 = UIView()
view1.superview!.addSubview(spacer1)
view1.superview!.addSubview(spacer2)
// Assume superview exists? Assume all views (view1, view2) are siblings

view1.right == spacer1.left
spacer1.right == view2.left
view2.right == spacer2.left
spacer2.right == view3.left

spacer1.width == spacer2.width
```

PS: `distribute` `by` `equal` `horizontally` doesn't sound very good. The syntax should probably be different.

**Comment by robb** [comment]
I think I'm pretty :-1: on mucking with the view hierachy as a side-effect. Too bad Auto Layout can't express `distance(view1.right, view2.left) == distance(view2.right, view3.left)`.

**Comment by truppelito** [comment]
> I think I'm pretty :-1: on mucking with the view hierachy as a side-effect.

I understand that perfectly. I think I'll stick to my own helper function for this then.

**Comment by robb** [comment]
> I think I'll stick to my own helper function for this then.

Feel free to gist it up and attach it to this discussion in case some is looking for something similar :sparkling_heart:

**Comment by truppelito** [comment]
[Here's](https://gist.github.com/truppelito/24fe8adaf1d997d49a90) the gist. It's not exactly what I was using, so I had to modify it a bit. And Xcode wasn't compiling anything, so I couldn't test it. If anyone's interested and finds a problem, feel free to leave a comment there.
