### ISSUE TITLE
Replacing groups doesn't work as expected

### ISSUE THREAD

**Issue by larcus94** [robb/Cartography#90]
I'm writing a layout that should change according to the current interface orientation of the device which is in my case an iPad.
The constraining is carried out by the a view controller that has a constraint group declared according to your example:
```swift
private var topicConstraints = ConstraintGroup()
```

The following method shows how I declare and replace the constraint groups to layout the subviews:

```swift
    func constrainTopicButtons(orientation: UIInterfaceOrientation) {
        var previousButton: TopicButton?
        let middleIndex = Double(self.topicButtons.count)/2.0
        let bounds = self.view.bounds
        
        for (i, button) in enumerate(self.topicButtons) {
            if orientation.isPortrait {
                let upperView = previousButton ?? self.avatarButton
                
                self.topicConstraints = constrain(view, upperView, button, replace: self.topicConstraints) { view, upperView, button in
                    button.centerX == view.centerX
                    button.top == upperView.bottom+50
                    button.width == view.width*0.6
                    button.height == 80
                }
            }
            else {
                self.topicConstraints = constrain(self.view, button, replace: self.topicConstraints) { view, button in
                    let index = Double(i)
                    if index == middleIndex {
                        button.centerX == view.centerX
                    }
                    else if index < middleIndex {
                        button.centerX <= view.centerX
                    }
                    else {
                        button.centerX == view.centerX
                    }
                    
                    button.bottom == view.bottom-120
                    button.width == 200
                    button.height == 130
                }
            }
            
            previousButton = button
        }
    }
```

While the code for the landscape mode is definitely broken (was just a little mock up to test it), the portrait should work. Indeed it actually does except that I have to remove the `replace` parameter of the `constraint` function. If I don't the layout is utterly broken. Nothing is logged indicating that a constraint was broken.

Am I replacing the groups in the wrong way? Would it be possible to make the `replace` parameter of `ConstraintGroup?` type so you could pass it nil when it's the first time its being laid out?

**Comment by robb** [comment]
> Am I replacing the groups in the wrong way?

I think what happens here is since you iterate over multiple buttons in `self.topicButtons`, you only ever going to end up with the last button property layouted, since you keep replacing the constraints set up by the previous iteration of the loop, e.g.:

```swift
let topicConstraints = ConstraintGroup()

let topicButtons = [ buttonA, buttonB, buttonC ]

for (i, button) in enumerate(topicButtons) {
    self.topicConstraints = constrain(button, replace: topicConstraints) { viewbutton in
        button.width == i * 100.0
    }
}
```

is equivalent to:

```
constrain(buttonA, replace: topicConstraints) { /* … */ }
constrain(buttonB, replace: topicConstraints) { /* … */ }
constrain(buttonC, replace: topicConstraints) { /* … */ }
```

which most likely isn't what you want. This also explains why it works if you remove the `replace` parameter.

`constrain` has a version that allows you to pass in an `Array` that you could use, something like

```swift
constrain([view, avatarView] + topicButtons) { proxies in
    let view = proxies[0]
    let avatarView = proxies[1]
    let topicButtons = proxies[2..<proxies.count]

    /* … */
}
```

> Would it be possible to make the `replace` parameter of `ConstraintGroup?` type so you could pass it nil when it's the first time its being laid out?

You can pass in an empty `ConstraintGroup` just fine, no need to optionalize it.

**Comment by larcus94** [comment]
Oh shit, was a long day yesterday. Sorry for taking your time with such a dumb issue :)

**Comment by robb** [comment]
No worries :ok_hand:
