### ISSUE TITLE
How to import Cartography to swift project?

### ISSUE THREAD

**Issue by chenenyu** [robb/Cartography#96]
:)

**Comment by dkrdennis** [comment]
:+1:

**Comment by robb** [comment]
Have you tried [Carthage](https://github.com/Carthage/Carthage).

**Comment by dkrdennis** [comment]
Hey

The problem was that Cocoapods doesn't support iOS 7, i haven't tried Carthage. 

But now i fixed my problem, all the Cartography swift files also needed "target membership" to my test target.

**Comment by robb** [comment]
:ok_hand:
